name = "aquila"
version = "0.1.0"
license = "license"
author = "Dominik Gronkiewicz"
maintainer = "gronki@gmail.com"
copyright = "Copyright 2024, Dominik Gronkiewicz"

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false
link = ["cfitsio", "png"]

[install]
library = false

[fortran]
source-form = "free"
implicit-external = true

[[executable]]
name = "aqstack"
source-dir = "app"
main = "aqstack.f90"

[[executable]]
name = "aqlrgb"
source-dir = "app"
main = "aqlrgb.F90"

[[executable]]
name = "aq2"
source-dir = "app/aq2"
main = "aq2.f90"

[[executable]]
name = "aqconvol"
source-dir = "app"
main = "aqconvol.f90"

[dependencies]
openmp = "*"
fastconv = {path = "deps/fastconv"}
aq2_task_dispatch = {path = "deps/task-dispatch"}
